#pragma once

void default_constants();

void drive_example();
void please_drive();
void turn_example();
void red_right();
void red_right2();
void red_right3();
void blue_left3();
void red_right4();
void red_right5();
void red_rightRightMid();
void red_rightRightCenter();
void blue_leftMid();
void blue_leftLeftCenter();
void blue_left();
void skills_attempt1();
void drive_and_turn();
void wait_until_change_speed();
void swing_example();
void motion_chaining();
void combining_movements();
void interfered_example();
void odom_drive_example();
void odom_pure_pursuit_example();
void odom_pure_pursuit_wait_until_example();
void odom_boomerang_example();
void odom_boomerang_injected_pure_pursuit_example();
void measure_offsets();
